import type { DiscoverCard } from './types'

export const mockCards: DiscoverCard[] = [
  {
    user_id: 'card-mc',
    display_name: 'Blocky',
    age: 22,
    bio: 'Minecraft builder & redstone nerd. SMP survival, the occasional Hypixel grind. Tap “View in 3D” 👀',
    gender: 'non-binary',
    intentions: ['casual', 'gaming_partner'],
    interests: [
      { id: 'cmi1', name: 'Minecraft', category: 'games' },
      { id: 'cmi2', name: 'Redstone', category: 'hobbies' },
      { id: 'cmi3', name: 'Building', category: 'art' },
      { id: 'cmi4', name: 'Lo-fi', category: 'music' },
    ],
    photos: [
      {
        id: 'cmp1',
        url: 'https://mc-heads.net/player/Technoblade/512',
        is_primary: true,
        order: 0,
        created_at: '2024-01-01T00:00:00Z',
        avatar_type: 'minecraft',
        avatar_username: 'Technoblade',
      },
      { id: 'cmp2', url: 'https://picsum.photos/seed/blocky/400/600', is_primary: false, order: 1, created_at: '2024-01-01T00:00:00Z' },
    ],
    voice_notes: [],
    cosmetic: null,
    badges: [],
    level: 5,
    compatibility_score: 89,
    shared_interests: [
      { id: 'cmi1', name: 'Minecraft', category: 'games' },
      { id: 'cmi4', name: 'Lo-fi', category: 'music' },
    ],
    distance_label: 'nearby',
  },
  {
    user_id: 'card-1',
    display_name: 'Aria',
    age: 21,
    bio: 'Valorant Platinum grinder by day, Minecraft builder by night. Looking for consistent duo partners.',
    gender: 'female',
    intentions: ['competitive', 'casual'],
    interests: [
      { id: 'c1i1', name: 'Valorant', category: 'games' },
      { id: 'c1i2', name: 'Minecraft', category: 'games' },
      { id: 'c1i3', name: 'Anime', category: 'anime' },
      { id: 'c1i4', name: 'Lo-fi', category: 'music' },
    ],
    photos: [
      { id: 'c1p1', url: 'https://picsum.photos/seed/aria1/400/600', is_primary: true, order: 0, created_at: '2024-01-01T00:00:00Z' },
      { id: 'c1p2', url: 'https://picsum.photos/seed/aria2/400/600', is_primary: false, order: 1, created_at: '2024-01-01T00:00:00Z' },
      {
        id: 'c1p3',
        url: 'https://mc-heads.net/player/jeb_/512',
        is_primary: false,
        order: 2,
        created_at: '2024-01-01T00:00:00Z',
        avatar_type: 'minecraft',
        avatar_username: 'jeb_',
      },
    ],
    voice_notes: [],
    cosmetic: null,
    badges: [],
    level: 5,
    compatibility_score: 87,
    shared_interests: [
      { id: 'c1i3', name: 'Anime', category: 'anime' },
      { id: 'c1i4', name: 'Lo-fi', category: 'music' },
    ],
    distance_label: 'nearby',
  },
  {
    user_id: 'card-2',
    display_name: 'Kai',
    age: 24,
    bio: 'Chill gamer, mainly play Apex and Rocket League. Into D&D and tabletop on weekends.',
    gender: 'male',
    intentions: ['chill', 'gaming_partner'],
    interests: [
      { id: 'c2i1', name: 'Apex Legends', category: 'games' },
      { id: 'c2i2', name: 'Rocket League', category: 'games' },
      { id: 'c2i3', name: 'D&D', category: 'hobbies' },
      { id: 'c2i4', name: 'Photography', category: 'hobbies' },
    ],
    photos: [
      { id: 'c2p1', url: 'https://picsum.photos/seed/kai1/400/600', is_primary: true, order: 0, created_at: '2024-01-01T00:00:00Z' },
    ],
    voice_notes: [
      { id: 'c2vn1', url: '', duration_seconds: 12, is_profile: false, created_at: '2024-01-01T00:00:00Z' },
    ],
    cosmetic: null,
    badges: [],
    level: 2,
    compatibility_score: 72,
    shared_interests: [
      { id: 'c2i4', name: 'Photography', category: 'hobbies' },
    ],
    distance_label: null,
  },
  {
    user_id: 'card-3',
    display_name: 'Nori',
    age: 22,
    bio: 'Marvel Rivals main and huge anime fan. Always looking for new shows and gaming buddies.',
    gender: 'non-binary',
    intentions: ['casual', 'chill'],
    interests: [
      { id: 'c3i1', name: 'Marvel Rivals', category: 'games' },
      { id: 'c3i2', name: 'Anime', category: 'anime' },
      { id: 'c3i3', name: 'Cooking', category: 'food' },
      { id: 'c3i4', name: 'Stardew Valley', category: 'games' },
    ],
    photos: [
      { id: 'c3p1', url: 'https://picsum.photos/seed/nori1/400/600', is_primary: true, order: 0, created_at: '2024-01-01T00:00:00Z' },
      { id: 'c3p2', url: 'https://picsum.photos/seed/nori2/400/600', is_primary: false, order: 1, created_at: '2024-01-01T00:00:00Z' },
      { id: 'c3p3', url: 'https://picsum.photos/seed/nori3/400/600', is_primary: false, order: 2, created_at: '2024-01-01T00:00:00Z' },
    ],
    voice_notes: [],
    cosmetic: null,
    badges: [],
    level: 4,
    compatibility_score: 94,
    shared_interests: [
      { id: 'c3i2', name: 'Anime', category: 'anime' },
      { id: 'c3i3', name: 'Cooking', category: 'food' },
      { id: 'c3i4', name: 'Stardew Valley', category: 'games' },
    ],
    distance_label: 'nearby',
  },
  {
    user_id: 'card-4',
    display_name: 'Dex',
    age: 26,
    bio: 'CS2 and Dota veteran. Gold-ranked, trying to climb. Prefer coordinated play with voice.',
    gender: 'male',
    intentions: ['competitive'],
    interests: [
      { id: 'c4i1', name: 'Counter-Strike 2', category: 'games' },
      { id: 'c4i2', name: 'Dota 2', category: 'games' },
      { id: 'c4i3', name: 'Fitness', category: 'fitness' },
      { id: 'c4i4', name: 'Technology', category: 'technology' },
    ],
    photos: [
      { id: 'c4p1', url: 'https://picsum.photos/seed/dex1/400/600', is_primary: true, order: 0, created_at: '2024-01-01T00:00:00Z' },
    ],
    voice_notes: [],
    cosmetic: null,
    badges: [],
    level: 7,
    compatibility_score: 58,
    shared_interests: [],
    distance_label: 'far away',
  },
  {
    user_id: 'card-5',
    display_name: 'Suki',
    age: 20,
    bio: 'Roblox dev + Overwatch 2 support main. Creative, artsy, loves lo-fi playlists while gaming.',
    gender: 'female',
    intentions: ['chill', 'gaming_partner'],
    interests: [
      { id: 'c5i1', name: 'Roblox', category: 'games' },
      { id: 'c5i2', name: 'Overwatch 2', category: 'games' },
      { id: 'c5i3', name: 'Lo-fi', category: 'music' },
      { id: 'c5i4', name: 'Art', category: 'art' },
    ],
    photos: [
      { id: 'c5p1', url: 'https://picsum.photos/seed/suki1/400/600', is_primary: true, order: 0, created_at: '2024-01-01T00:00:00Z' },
      { id: 'c5p2', url: 'https://picsum.photos/seed/suki2/400/600', is_primary: false, order: 1, created_at: '2024-01-01T00:00:00Z' },
    ],
    voice_notes: [],
    cosmetic: null,
    badges: [],
    level: 3,
    compatibility_score: 81,
    shared_interests: [
      { id: 'c5i3', name: 'Lo-fi', category: 'music' },
    ],
    distance_label: 'nearby',
  },
  {
    user_id: 'card-6',
    display_name: 'Remy',
    age: 25,
    bio: 'Helldivers 2 squad looking for stragglers. Also play Destiny 2 raids on weekends.',
    gender: 'male',
    intentions: ['casual', 'gaming_partner'],
    interests: [
      { id: 'c6i1', name: 'Helldivers 2', category: 'games' },
      { id: 'c6i2', name: 'Destiny 2', category: 'games' },
      { id: 'c6i3', name: 'Travel', category: 'travel' },
      { id: 'c6i4', name: 'Food', category: 'food' },
    ],
    photos: [
      { id: 'c6p1', url: 'https://picsum.photos/seed/remy1/400/600', is_primary: true, order: 0, created_at: '2024-01-01T00:00:00Z' },
    ],
    voice_notes: [
      { id: 'c6vn1', url: '', duration_seconds: 18, is_profile: false, created_at: '2024-01-01T00:00:00Z' },
    ],
    cosmetic: null,
    badges: [],
    level: 6,
    compatibility_score: 65,
    shared_interests: [
      { id: 'c6i4', name: 'Food', category: 'food' },
    ],
    distance_label: null,
  },
  {
    user_id: 'card-7',
    display_name: 'Yuna',
    age: 23,
    bio: 'League support/jungle flex. Silver climbing to gold. Chill vibes, no flaming.',
    gender: 'female',
    intentions: ['competitive', 'casual'],
    interests: [
      { id: 'c7i1', name: 'League of Legends', category: 'games' },
      { id: 'c7i2', name: 'Anime', category: 'anime' },
      { id: 'c7i3', name: 'Reading', category: 'reading' },
      { id: 'c7i4', name: 'Music', category: 'music' },
    ],
    photos: [
      { id: 'c7p1', url: 'https://picsum.photos/seed/yuna1/400/600', is_primary: true, order: 0, created_at: '2024-01-01T00:00:00Z' },
      { id: 'c7p2', url: 'https://picsum.photos/seed/yuna2/400/600', is_primary: false, order: 1, created_at: '2024-01-01T00:00:00Z' },
    ],
    voice_notes: [],
    cosmetic: null,
    badges: [],
    level: 4,
    compatibility_score: 76,
    shared_interests: [
      { id: 'c7i2', name: 'Anime', category: 'anime' },
    ],
    distance_label: 'nearby',
  },
  {
    user_id: 'card-8',
    display_name: 'Vex',
    age: 27,
    bio: 'Fortnite builder / zero-build. Chill night sessions. Open to trying new games.',
    gender: 'other',
    intentions: ['chill'],
    interests: [
      { id: 'c8i1', name: 'Fortnite', category: 'games' },
      { id: 'c8i2', name: 'Movies', category: 'movies' },
      { id: 'c8i3', name: 'Sports', category: 'sports' },
    ],
    photos: [
      { id: 'c8p1', url: 'https://picsum.photos/seed/vex1/400/600', is_primary: true, order: 0, created_at: '2024-01-01T00:00:00Z' },
    ],
    voice_notes: [],
    cosmetic: null,
    badges: [],
    level: 1,
    compatibility_score: 49,
    shared_interests: [],
    distance_label: 'far away',
  },
]
